// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_v7qgUVl34_8RHdpl1JQfyx1R-hhhp0',
    appId: '1:388226828119:web:c82d677771343ee9bda012',
    messagingSenderId: '388226828119',
    projectId: 'techstore-22eae',
    authDomain: 'techstore-22eae.firebaseapp.com',
    storageBucket: 'techstore-22eae.firebasestorage.app',
    measurementId: 'G-1R75NE6B1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0pe7OFG9ZHY-mfcgxJ5GqPN-YEnQEOg',
    appId: '1:269901162260:android:4a1576bc810d0bf45dc401',
    messagingSenderId: '269901162260',
    projectId: 'techstore-bb02f',
    storageBucket: 'techstore-bb02f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQleaTynioKwi7-FZ70l2tcMAXtCOOv6s',
    appId: '1:269901162260:ios:7e2420b314c288fd5dc401',
    messagingSenderId: '269901162260',
    projectId: 'techstore-bb02f',
    storageBucket: 'techstore-bb02f.firebasestorage.app',
    iosBundleId: 'com.example.onus2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQleaTynioKwi7-FZ70l2tcMAXtCOOv6s',
    appId: '1:269901162260:ios:7e2420b314c288fd5dc401',
    messagingSenderId: '269901162260',
    projectId: 'techstore-bb02f',
    storageBucket: 'techstore-bb02f.firebasestorage.app',
    iosBundleId: 'com.example.onus2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7QTmnJWvqAh3FGX0d_xlZCjEuT_VAnvE',
    appId: '1:269901162260:web:f66ca8b773c889fd5dc401',
    messagingSenderId: '269901162260',
    projectId: 'techstore-bb02f',
    authDomain: 'techstore-bb02f.firebaseapp.com',
    storageBucket: 'techstore-bb02f.firebasestorage.app',
    measurementId: 'G-3Z33QHQYLN',
  );
}